### ISSUE TITLE
Any way to play without origin

### ISSUE THREAD

**Issue by CyferShepard** [PrivateServerEmulator/ME3PSE#3]
I legally own the game and I'm willing to show proof so that you don't get the impression that I'm trying to pirate, but I only receive 20 gigs of data a month and I don't want to waste it keeping origin open every time. Is there a way to play without opening origin and if so how?

**Comment by Erik-JS** [comment]
Can't you just block Origin though a firewall? That should force it into offline mode.

In order to completely avoid Origin, you'll have to get a cracked EXE. Off the top of my head, the original MassEffect3.exe is supposed to run a piece of DRM-specific code which calls awc.dll in the Core folder, and then the Origin client is launched/checked to verify ownership of the game, so the rest of the EXE can be unpacked in the memory.

Note that the cracked game still communicates with EA's server (MP will be playable if you have valid credentials saved in Local_profile.sav). If you want absolutely no communication, then block the cracked EXE through a firewall.

**Now, I don't want to sound like an ass, but this issue section is supposed to be about issues with PSE, caused either by or because of PSE. For general questions about the game not related to PSE, please visit ME3 Tweaks Forums: https://me3tweaks.com/forums/**

I won't close this issue just yet, though. If you still need help on this issue (playing the game without Origin), then please feel free to keep posting here.
