### ISSUE TITLE
Reading of player data

### ISSUE THREAD

**Issue by GamerClassN7** [PrivateServerEmulator/ME3PSE#5]
Hi, is there any way how to read data from mp macht like last played map, enemy, difficulty ? 

P.S. sorry for posting it like issue but I don't know any other way how to contact you :(

**Comment by Erik-JS** [comment]
As I said in the previous issue, anything unrelated to problems caused by PSE should be posted in https://me3tweaks.com/forums/.

There's something called "lobby setup" (not sure what its real name is, I just called it that after I found it) which appears in game's memory when the player joins a lobby/match.

From my Cheat Engine table: "MassEffect3.exe"+0152698C<br />
(assuming game base address is 0x400000, then: 0x400000 + 0x152698C = 0x192698C)

0x192698C is a pointer to lobby setup (if its value is 0, then player is not in a match/lobby).

Is this "lobby setup" what you're looking for? (I can dig up more stuff later)

**Comment by GamerClassN7** [comment]
i am looking for 4 values for start map name, enemy name & difficulty. unforchunatly i cant download Cheat Engine both sites and software is blocked by Antivirus

**Comment by GamerClassN7** [comment]
Do you have Discord, Messenger, Hangout, or something similar where we can meet and i can ask you some question.

**Comment by GamerClassN7** [comment]
i was able to find address of map and difficulty using "HeapMem View" (from what i see it is same like cheat engine :D) but every time i run game address is different :(

**Comment by Erik-JS** [comment]
You tried downloading Cheat Engine through its [GitHub page](https://github.com/cheat-engine/cheat-engine), right?

Cheat Engine has a pointer scanner for addresses that keep changing. If you still can't download/run Cheat Engine, I'd suggest looking for another memory editor with pointer scanning.

You can contact me through Origin (ErikJS_BR) or Steam (Erik_JS).

**Comment by GamerClassN7** [comment]
I send Friend Request to you on Origin :)

ne 9. 12. 2018 v 22:08 odesílatel Erik JS <notifications@github.com> napsal:
